### ISSUE TITLE
initd plugin not working on Ubuntu 14.04

### ISSUE THREAD

**Issue by bcowdery** [benediktschmitt/emsm#59]
initd script fails on boot with the error: **Cannot make directory '/var/run/screen': Permission denied**

The configuraiton for Ubuntu is a little different than in the plugin docs, the scripts were installed with:
`
sudo update-rc.d minecraft defaults
sudo update-rc.d minecraft enable
`

**Comment by benediktschmitt** [comment]
I think this is a bug in Ubuntu: 
https://bugs.launchpad.net/ubuntu/+source/screen/+bug/1380080
https://bugs.launchpad.net/ubuntu/+source/screen/+bug/574773

I added a *systemd* script to EMSM, which can be edited, to make sure the *screen.service* starts before EMSM.

(If this issue can not be fixed with the *systemd* script, feel free to reopen it or leave a comment.)
